### ISSUE TITLE
Guid::uuid4() doesn't generate a Guid

### ISSUE THREAD

**Issue by prolic** [ramsey/uuid#306]
`echo get_class(Ramsey\Uuid\Guid\Guid::uuid4());`

will return

`Ramsey\Uuid\Rfc4122\UuidV4`.

I didn't expect this behavior at all.

**Comment by prolic** [comment]
Also consider this:

```
$f = new Ramsey\Uuid\UuidFactory(new Ramsey\Uuid\FeatureSet(true));

var_dump($f->uuid4());
```

will return:

`PHP Fatal error:  Uncaught Ramsey\Uuid\Exception\InvalidArgumentException: The byte string received does not contain a valid version in vendor/ramsey/uuid/src/Guid/Fields.php:83`

**Comment by ramsey** [comment]
Are these two different issues, or do you consider them related?

As for the 1st issue, please see #301. The static methods are not part of the interface and should not be used from the subclasses. This is a bug. I’m sorry for the confusion.

**Comment by prolic** [comment]
As I am trying to create Guids in both cases, those issues are related to
me, maybe from a technical perspective they aren't for you.

I can create separate issues if you want to.

**Comment by ramsey** [comment]
The first issue is an oversight on my part. You should not have access to `Guid::uuid4()`. This is a bug. Only the `Ramsey\Uuid\Uuid` class should have the static methods. I will roll out a release soon that disables these static methods on child classes (they are only child classes for the sake of BC and easy transition from version 3 to 4; they will no longer be child classes in version 5).

I’ll look into the second issue. At a glance, this looks like it should work, so I think you’ve uncovered another bug here.

Thanks!

**Comment by prolic** [comment]
> $f = new Ramsey\Uuid\UuidFactory(new Ramsey\Uuid\FeatureSet(true));
> 
> var_dump($f->uuid4());

This is solved in master branch already, not working on 4.0.1 though.

**Comment by ramsey** [comment]
The master branch is the same as 4.0.1 right now. The only difference is white space. How can this work in master and not in 4.0.1?

**Comment by prolic** [comment]
Can't tell, that's what I tried. Don't trust, verify.

**Comment by enumag** [comment]
@ramsey It's not fixed. The bug just doesn't always appear, it's random. I posted more details in the separate issue: https://github.com/ramsey/uuid/issues/314#issuecomment-734339547
